import { Providers } from "./providers";
import type { Metadata } from "next";
import "../styles/globals.css";
export const metadata: Metadata = {
  title: "Mini AI Note App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
